const conditions = [
  {
    id: 1,
    code: "A09",
    description: "Infectious gastroenteritis and colitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    code: "A64",
    description: "Unspecified sexually transmitted disease",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    code: "B300",
    description: "Keratoconjunctivitis due to adenovirus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    code: "B302",
    description: "Viral pharyngoconjunctivitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    code: "B308",
    description: "Other viral conjunctivitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    code: "B309",
    description: "Viral conjunctivitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    code: "B373",
    description: "Candidiasis of vulva and vagina",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    code: "B9789",
    description:
      "Other viral agents as the cause of diseases classified elsewhere",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    code: "E860",
    description: "Dehydration",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    code: "F340",
    description: "Cyclothymic disorder",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    code: "F341",
    description: "Dysthymic disorder",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1,
    code: "F39",
    description: "Unspecified mood [affective] disorder",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    code: "F411",
    description: "Generalized anxiety disorder",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    code: "F418",
    description: "Other specified anxiety disorders",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    code: "F419",
    description: "Anxiety disorder, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    code: "F4321",
    description: "Adjustment disorder with depressed mood",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    code: "G43001",
    description:
      "Migraine without aura, not intractable, with status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    code: "G43009",
    description:
      "Migraine without aura, not intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    code: "G43019",
    description:
      "Migraine without aura, intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    code: "G43501",
    description:
      "Persistent migraine aura without cerebral infarction, not intractable, with status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    code: "G43509",
    description:
      "Persistent migraine aura without cerebral infarction, not intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 22,
    code: "G43519",
    description:
      "Persistent migraine aura without cerebral infarction, intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    code: "G43701",
    description:
      "Chronic migraine without aura, not intractable, with status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 24,
    code: "G43709",
    description:
      "Chronic migraine without aura, not intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    code: "G43711",
    description:
      "Chronic migraine without aura, intractable, with status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 26,
    code: "G43719",
    description:
      "Chronic migraine without aura, intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 27,
    code: "G43809",
    description: "Other migraine, not intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 28,
    code: "G43811",
    description: "Other migraine, intractable, with status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 29,
    code: "G43819",
    description: "Other migraine, intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 30,
    code: "G43829",
    description:
      "Menstrual migraine, not intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 31,
    code: "G43909",
    description:
      "Migraine, unspecified, not intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 32,
    code: "G43911",
    description: "Migraine, unspecified, intractable, with status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 33,
    code: "G43919",
    description:
      "Migraine, unspecified, intractable, without status migrainosus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 34,
    code: "G44209",
    description: "Tension-type headache, unspecified, not intractable",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 35,
    code: "G44219",
    description: "Episodic tension-type headache, not intractable",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 36,
    code: "G4700",
    description: "Insomnia, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 37,
    code: "G4701",
    description: "Insomnia due to medical condition",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 38,
    code: "G5600",
    description: "Carpal tunnel syndrome, unspecified upper limb",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 39,
    code: "H10029",
    description: "Other mucopurulent conjunctivitis, unspecified eye",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 40,
    code: "H1033",
    description: "Unspecified acute conjunctivitis, bilateral",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 41,
    code: "H1044",
    description: "Vernal conjunctivitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 42,
    code: "H1045",
    description: "Other chronic allergic conjunctivitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 43,
    code: "H10509",
    description: "Unspecified blepharoconjunctivitis, unspecified eye",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 44,
    code: "H10819",
    description: "Pingueculitis, unspecified eye",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 45,
    code: "H1089",
    description: "Other conjunctivitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 46,
    code: "H109",
    description: "Unspecified conjunctivitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 47,
    code: "H6020",
    description: "Malignant otitis externa, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 48,
    code: "H60339",
    description: "Swimmer's ear, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 49,
    code: "H60399",
    description: "Other infective otitis externa, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 50,
    code: "H6500",
    description: "Acute serous otitis media, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 51,
    code: "H65119",
    description:
      "Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 52,
    code: "H65199",
    description: "Other acute nonsuppurative otitis media, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 53,
    code: "H6520",
    description: "Chronic serous otitis media, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 54,
    code: "H65499",
    description: "Other chronic nonsuppurative otitis media, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 55,
    code: "H6590",
    description: "Unspecified nonsuppurative otitis media, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 56,
    code: "H66009",
    description:
      "Acute suppurative otitis media without spontaneous rupture of ear drum, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 57,
    code: "H66019",
    description:
      "Acute suppurative otitis media with spontaneous rupture of ear drum, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 58,
    code: "H663X9",
    description: "Other chronic suppurative otitis media, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 59,
    code: "H6640",
    description: "Suppurative otitis media, unspecified, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 60,
    code: "H6690",
    description: "Otitis media, unspecified, unspecified ear",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 61,
    code: "J00",
    description: "Acute nasopharyngitis [common cold]",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 62,
    code: "J0100",
    description: "Acute maxillary sinusitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 63,
    code: "J0110",
    description: "Acute frontal sinusitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 64,
    code: "J0130",
    description: "Acute sphenoidal sinusitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 65,
    code: "J0140",
    description: "Acute pansinusitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 66,
    code: "J0190",
    description: "Acute sinusitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 67,
    code: "J029",
    description: "Acute pharyngitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 68,
    code: "J060",
    description: "Acute laryngopharyngitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 69,
    code: "J069",
    description: "Acute upper respiratory infection, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 70,
    code: "J209",
    description: "Acute bronchitis, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 71,
    code: "J301",
    description: "Allergic rhinitis due to pollen",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 72,
    code: "J3081",
    description: "Allergic rhinitis due to animal (cat) (dog) hair and dander",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 73,
    code: "J36",
    description: "Peritonsillar abscess",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 74,
    code: "J40",
    description: "Bronchitis, not specified as acute or chronic",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 75,
    code: "J411",
    description: "Mucopurulent chronic bronchitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 76,
    code: "J42",
    description: "Unspecified chronic bronchitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 77,
    code: "J45901",
    description: "Unspecified asthma with (acute) exacerbation",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 78,
    code: "J45902",
    description: "Unspecified asthma with status asthmaticus",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 79,
    code: "K210",
    description: "Gastro-esophageal reflux disease with esophagitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 80,
    code: "K219",
    description: "Gastro-esophageal reflux disease without esophagitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 81,
    code: "K2900",
    description: "Acute gastritis without bleeding",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 82,
    code: "K2920",
    description: "Alcoholic gastritis without bleeding",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 83,
    code: "K2960",
    description: "Other gastritis without bleeding",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 84,
    code: "K5900",
    description: "Constipation, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 85,
    code: "K5901",
    description: "Slow transit constipation",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 86,
    code: "K5902",
    description: "Outlet dysfunction constipation",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 87,
    code: "K649",
    description: "Unspecified hemorrhoids",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 88,
    code: "K8019",
    description:
      "Calculus of gallbladder with other cholecystitis with obstruction",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 89,
    code: "K8020",
    description:
      "Calculus of gallbladder without cholecystitis without obstruction",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 90,
    code: "K8021",
    description:
      "Calculus of gallbladder without cholecystitis with obstruction",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 91,
    code: "K8042",
    description:
      "Calculus of bile duct with acute cholecystitis without obstruction",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 92,
    code: "K8050",
    description:
      "Calculus of bile duct without cholangitis or cholecystitis without obstruction",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 93,
    code: "K8051",
    description:
      "Calculus of bile duct without cholangitis or cholecystitis with obstruction",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 94,
    code: "L240",
    description: "Irritant contact dermatitis due to detergents",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 95,
    code: "L242",
    description: "Irritant contact dermatitis due to solvents",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 96,
    code: "L250",
    description: "Unspecified contact dermatitis due to cosmetics",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 97,
    code: "L251",
    description:
      "Unspecified contact dermatitis due to drugs in contact with skin",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 98,
    code: "L253",
    description:
      "Unspecified contact dermatitis due to other chemical products",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 99,
    code: "L255",
    description: "Unspecified contact dermatitis due to plants, except food",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 100,
    code: "L259",
    description: "Unspecified contact dermatitis, unspecified cause",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 101,
    code: "M25539",
    description: "Pain in unspecified wrist",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 102,
    code: "M5430",
    description: "Sciatica, unspecified side",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 103,
    code: "N730",
    description: "Acute parametritis and pelvic cellulitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 104,
    code: "N733",
    description: "Female acute pelvic peritonitis",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 105,
    code: "N739",
    description: "Female pelvic inflammatory disease, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 106,
    code: "N912",
    description: "Amenorrhea, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 107,
    code: "N920",
    description: "Excessive and frequent menstruation with regular cycle",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 108,
    code: "N921",
    description: "Excessive and frequent menstruation with irregular cycle",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 109,
    code: "N924",
    description: "Excessive bleeding in the premenopausal period",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 110,
    code: "N930",
    description: "Postcoital and contact bleeding",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 111,
    code: "N946",
    description: "Dysmenorrhea, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 112,
    code: "R079",
    description: "Chest pain, unspecified",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 113,
    code: "R109",
    description: "Unspecified abdominal pain",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 114,
    code: "R21",
    description: "Rash and other nonspecific skin eruption",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 115,
    code: "R42",
    description: "Dizziness and giddiness",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 116,
    code: "S53449A",
    description:
      "Ulnar collateral ligament sprain of unspecified elbow, initial encounter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 117,
    code: "S63519A",
    description:
      "Sprain of carpal joint of unspecified wrist, initial encounter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 118,
    code: "S63599A",
    description:
      "Other specified sprain of unspecified wrist, initial encounter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 119,
    code: "S638X9A",
    description:
      "Sprain of other part of unspecified wrist and hand, initial encounter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 120,
    code: "S93419A",
    description:
      "Sprain of calcaneofibular ligament of unspecified ankle, initial encounter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 121,
    code: "S93429A",
    description:
      "Sprain of deltoid ligament of unspecified ankle, initial encounter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 122,
    code: "S93439A",
    description:
      "Sprain of tibiofibular ligament of unspecified ankle, initial encounter",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

exports.conditions = conditions;
